/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import LocalizedLabel from "./i18n/LocalizedLabel"
import FingerView from "./game/ui/FingerView"
import GameUI from "./script/GameUI"
/*
* 游戏初始化配置;
*/
export default class GameConfig{
    static width:number=1920;
    static height:number=1080;
    static scaleMode:string="fixedheight";
    static screenMode:string="horizontal";
    static alignV:string="top";
    static alignH:string="left";
    static startScene:any="game/CommonTipDialog.scene";
    static sceneRoot:string="";
    static debug:boolean=false;
    static stat:boolean=false;
    static physicsDebug:boolean=false;
    static exportSceneToJson:boolean=true;
    constructor(){}
    static init(){
        var reg: Function = Laya.ClassUtils.regClass;
        reg("i18n/LocalizedLabel.ts",LocalizedLabel);
        reg("game/ui/FingerView.ts",FingerView);
        reg("script/GameUI.ts",GameUI);
    }
}
GameConfig.init();